Name: deploy-aws-pipeline

on:
  push:
    branches:
      - main

jobs:
  create-buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Execute python script to create buckets on the s3 aws server
        uses: actions/setup-python@v4
          with:python-version:'3.9'
        run: |
          echo 'Creating buckets'
          python src/create-buckets.py